#!/usr/bin/env python3
"""
Derive `_data/documentos.yml` from the PDFs actually present in `files/`.

The site's document list must not be maintained by hand. Page counts and file sizes
drift the moment a PDF is replaced, and a stale "72 pages / 3.0 MB" next to a document
that is now 8.7 MB is a small lie on a page whose entire purpose is to be trusted.

So: the file system is the source of truth for *derived* facts (which documents exist,
their page count, their size), and this script reconciles the data file against it.
Everything a human writes -- title, year, kind, language, summary -- is preserved
across runs and is never overwritten.

Workflow:

    python3 scripts/scan_documents.py                # reconcile
    python3 scripts/scan_documents.py --check        # verify only, no writes
    python3 scripts/scan_documents.py --apply-metadata   # also set PDF /Title, /Author, /Lang

Add a PDF, run the script, then fill in its human fields once. Re-running is always
safe: derived fields are refreshed, hand-written fields survive.

Exit codes: 0 success, 1 validation failure, 2 usage error.
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Install it with: pip install pyyaml")

SITE_ROOT = Path(__file__).resolve().parent.parent
FILES_DIR = SITE_ROOT / "files"
MANIFEST = SITE_ROOT / "_data" / "documentos.yml"

# Order in which keys are written. Derived keys first so a reader sees provenance
# before prose; `summary` last because it is the longest free-text field.
KEY_ORDER = [
    "id",
    "title",
    "year",
    "kind",
    "lang",
    "doi",
    "record_url",
    "file",
    "pages",
    "bytes",
    "size",
    "summary",
]

# Written to every run. Explains in the file itself that hand edits survive,
# which is the property a future maintainer most needs to know.
MANIFEST_HEADER = """# Public documents linked from the site.
#
# GENERATED by `scripts/scan_documents.py` -- but not blindly.
#
#   Derived from the file system, refreshed on every run:
#       id, file, pages, bytes, size
#
#   Written by hand, preserved on every run:
#       title, year, kind, lang, doi, record_url, summary
#
# The `id` is the path under files/ with the extension dropped and separators
# replaced by hyphens, so files/bachelor-thesis-unican.pdf -> bachelor-thesis-unican.
# Entries in _data/titulos.yml and _data/experiencia.yml reference documents through
# a `docs:` list of these ids.
#
# To add a document: copy the PDF into files/ with a kebab-case name, run
# `python3 scripts/scan_documents.py`, then fill in its hand-written fields.
# To verify without writing anything: `python3 scripts/scan_documents.py --check`.
#
# See files/README.md for what must never be placed here.
"""


def human_size(num_bytes):
    """Format a byte count for display. Matches what a visitor would expect."""
    if num_bytes < 1024:
        return f"{num_bytes} B"
    value = num_bytes / 1024
    for unit in ("KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            if value < 10:
                return f"{value:.1f} {unit}"
            return f"{value:.0f} {unit}"
        value /= 1024
    return f"{value:.1f} GB"


def pdfinfo(path):
    """
    Return a dict of fields for `path`, or None if it is not a readable PDF.

    Parsed by hand rather than with a YAML/PDF library so the script has no
    dependency beyond PyYAML. Only the fields the site actually displays are
    read; the `:` split is safe because none of them contain a colon followed
    by a space, which is the condition YAML needs for a bare scalar.
    """
    try:
        import subprocess

        result = subprocess.run(
            ["pdfinfo", str(path)],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("pdfinfo not found. Install poppler-utils (Debian/Ubuntu: apt install poppler-utils).")
    except subprocess.CalledProcessError as exc:
        print(f"  ! pdfinfo failed for {path.name}: {exc.stderr.strip()}", file=sys.stderr)
        return None

    wanted = {
        "Pages": "pages",
        "Encrypted": "encrypted",
        "JavaScript": "javascript",
        "Tagged": "tagged",
    }
    info = {}
    for line in result.stdout.splitlines():
        key, _, value = line.partition(":")
        key = key.strip()
        if key in wanted:
            info[wanted[key]] = value.strip()

    if info.get("encrypted", "no") != "no":
        print(f"  ! {path.name}: encrypted, refusing to publish", file=sys.stderr)
        return None
    if info.get("javascript", "no") != "no":
        print(f"  ! {path.name}: contains JavaScript", file=sys.stderr)
    if not info.get("pages"):
        print(f"  ! {path.name}: no page count, skipping", file=sys.stderr)
        return None
    return info


def scan_files():
    """Return {id: absolute Path} for every PDF under files/, recursively."""
    if not FILES_DIR.is_dir():
        return {}

    found = {}
    for path in sorted(FILES_DIR.rglob("*.pdf")):
        rel = path.relative_to(FILES_DIR).with_suffix("")
        doc_id = re.sub(r"[^a-z0-9]+", "-", rel.as_posix().lower()).strip("-")
        if doc_id in found:
            print(
                f"  ! duplicate id '{doc_id}': {found[doc_id].name} and {path.name}",
                file=sys.stderr,
            )
            continue
        found[doc_id] = path
    return found


def load_manifest():
    """Existing manifest as a list of dicts, or [] if absent."""
    if not MANIFEST.exists():
        return []
    with MANIFEST.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    return data or []


def site_author_name():
    """Read author.name from _config.yml so the name has exactly one home."""
    config = SITE_ROOT / "_config.yml"
    if not config.exists():
        return None
    with config.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    return ((data.get("author") or {}).get("name")) or None


def build(found, previous):
    """
    Merge discovered files with the previous manifest.

    Derived fields always come from the file system. Hand-written fields come from
    the previous manifest, and a field that was empty stays empty rather than being
    filled with a guess -- an empty `title` is visibly unfinished, a wrong one is
    silently wrong.
    """
    by_id = {entry.get("id"): entry for entry in previous if entry.get("id")}
    records = []
    dropped = []

    for doc_id, path in found.items():
        info = pdfinfo(path)
        if info is None:
            continue

        size_bytes = path.stat().st_size
        record = {
            "id": doc_id,
            "file": f"files/{path.relative_to(FILES_DIR).as_posix()}",
            "pages": int(info["pages"]),
            "bytes": size_bytes,
            "size": human_size(size_bytes),
        }

        old = by_id.get(doc_id, {})
        for field in ("title", "year", "kind", "lang", "doi", "record_url", "summary"):
            value = old.get(field)
            if value not in (None, ""):
                record[field] = value

        records.append(record)

    for doc_id in by_id:
        if doc_id not in found:
            dropped.append(doc_id)

    records.sort(key=lambda item: (-(item.get("year") or 0), item["id"]))
    return records, dropped


def dump(records):
    lines = [MANIFEST_HEADER]
    if not records:
        lines.append("# (no PDFs found under files/)\n")
        return "\n".join(lines)

    for record in records:
        ordered = {key: record[key] for key in KEY_ORDER if key in record}
        block = yaml.safe_dump(
            [ordered], sort_keys=False, allow_unicode=True, default_flow_style=False, width=88
        )
        # safe_dump on a one-item list yields a leading "- "; keep it, it is valid YAML
        # and matches the list shape used by the other _data files.
        lines.append(block.rstrip("\n"))
        lines.append("")
    return "\n".join(lines)


def check(manifest, found):
    """
    Validate the manifest *as it sits on disk* against the file system and the data
    files that link to it.

    Reading the on-disk manifest rather than a freshly rebuilt one is the whole point.
    An earlier version of this function checked the rebuilt records, which meant a PDF
    that had been deleted was dropped from the list before validation ever ran and
    `--check` reported success. The manifest is the artifact under test, so it has to be
    the artifact that gets read.

    Catches the four mistakes that are easy to make and invisible until the site is
    live: a `docs:` id with no document, a document file that is gone, a PDF added to
    `files/` but never indexed, and a replaced PDF whose recorded page count or size no
    longer matches the file.
    """
    problems = []
    manifest_ids = set()

    for record in manifest:
        doc_id = record.get("id")
        if not doc_id:
            problems.append("manifest contains an entry with no 'id'")
            continue
        if doc_id in manifest_ids:
            problems.append(f"manifest has a duplicate id '{doc_id}'")
            continue
        manifest_ids.add(doc_id)

        rel = record.get("file")
        if not rel:
            problems.append(f"document '{doc_id}' has no 'file'")
        elif not (SITE_ROOT / rel).exists():
            problems.append(f"document '{doc_id}' points at missing file {rel}")

        for field in ("title", "year", "kind", "lang", "summary"):
            if not record.get(field):
                problems.append(f"document '{doc_id}' has no '{field}' yet")

        # A citable identifier is worth nothing if it is a typo, and a citation is a
        # promise to a reader. Checked by shape only -- no network call -- so `--check`
        # stays hermetic and usable in CI. Resolution was verified by hand for the
        # entries that carry a doi.
        doi = record.get("doi")
        if doi and not re.fullmatch(r"https://doi\.org/10\.\d{4,9}/\S+", doi):
            problems.append(
                f"document '{doc_id}' has a malformed doi {doi!r} "
                f"(expected https://doi.org/10.NNNN/suffix)"
            )
        record_url = record.get("record_url")
        if record_url and not record_url.startswith("https://"):
            problems.append(
                f"document '{doc_id}' has a non-https record_url {record_url!r}"
            )

    # The other direction: anything in files/ that the manifest does not describe, and
    # any entry whose derived fields have drifted away from the actual file.
    for doc_id, path in sorted(found.items()):
        if doc_id not in manifest_ids:
            problems.append(
                f"files/{path.name} is not in the manifest -- run scan_documents.py"
            )
            continue

        record = next(item for item in manifest if item.get("id") == doc_id)
        info = pdfinfo(path)
        if info is None:
            problems.append(f"files/{path.name} could not be read as an unencrypted PDF")
            continue

        size_bytes = path.stat().st_size
        for field, actual in (("pages", int(info["pages"])), ("bytes", size_bytes),
                              ("size", human_size(size_bytes))):
            if field in record and record[field] != actual:
                problems.append(
                    f"document '{doc_id}' records {field}={record[field]!r} "
                    f"but the file is {actual!r} -- run scan_documents.py"
                )

    for data_name in ("titulos.yml", "experiencia.yml"):
        path = SITE_ROOT / "_data" / data_name
        if not path.exists():
            continue
        with path.open(encoding="utf-8") as handle:
            entries = yaml.safe_load(handle) or []

        def walk(node, trail):
            if isinstance(node, dict):
                for key, value in node.items():
                    if key == "docs":
                        for doc_id in value or []:
                            if doc_id not in manifest_ids:
                                problems.append(
                                    f"_data/{data_name} {trail}: docs '{doc_id}' has no document in files/"
                                )
                    walk(value, f"{trail}.{key}")
            elif isinstance(node, list):
                for index, item in enumerate(node):
                    walk(item, f"{trail}[{index}]")

        walk(entries, "")

    return problems


def apply_metadata(records):
    """
    Write /Title, /Author, /Subject and /Lang into each PDF.

    Rationale: the LaTeX originals have empty metadata, so a browser tab shows
    "master-thesis-desy.pdf" and a screen reader announces the document with no
    language hint. /Lang in particular makes assistive technology pronounce a
    Spanish document in Spanish. Creator/Producer (pdfTeX, MiKTeX) are left alone --
    they identify the toolchain, not the author, and rewriting them risks
    invalidating a document the user may want to submit somewhere.
    """
    try:
        from pypdf import PdfReader, PdfWriter
        from pypdf.generic import NameObject, TextStringObject
    except ImportError:
        sys.exit("pypdf is required for --apply-metadata. Install it with: pip install pypdf")

    author = site_author_name()
    for record in records:
        path = SITE_ROOT / record["file"]
        writer = PdfWriter()
        reader = PdfReader(str(path))
        for page in reader.pages:
            writer.add_page(page)

        info = {
            "/Title": record.get("title") or record["id"],
            "/Author": author or "",
            "/Subject": record.get("summary", "") or "",
            "/Keywords": record.get("kind", "") or "",
        }
        writer.add_metadata(info)

        language = record.get("lang")
        if language:
            # Catalog-level /Lang. This is what assistive technology reads.
            writer.root_object[NameObject("/Lang")] = TextStringObject(language)

        with open(path, "wb") as handle:
            writer.write(handle)
        print(f"  metadata written: {record['id']} (Lang={language or 'unset'})")


def main():
    parser = argparse.ArgumentParser(
        description="Reconcile _data/documentos.yml with the PDFs in files/."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate without writing anything; exit 1 on problems",
    )
    parser.add_argument(
        "--apply-metadata",
        action="store_true",
        help="also write /Title, /Author, /Subject and /Lang into each PDF",
    )
    args = parser.parse_args()

    found = scan_files()
    if not found:
        if args.check:
            print("FAILED", file=sys.stderr)
            print("  - no PDFs under files/, but the site may still link to them", file=sys.stderr)
            return 1
        print("No PDFs under files/. Nothing to do.")
        return 0

    on_disk = load_manifest()

    if args.check:
        # Deliberately the on-disk manifest, not a rebuild: see check().
        problems = check(on_disk, found)
        if problems:
            print("FAILED", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1
        print(f"OK: {len(on_disk)} document(s) consistent.")
        return 0

    records, dropped = build(found, on_disk)

    for doc_id in dropped:
        print(f"  ! '{doc_id}' was removed from files/ and dropped from the manifest", file=sys.stderr)

    if args.apply_metadata:
        apply_metadata(records)
        # Re-read: pypdf rewrote the files, so sizes and page counts may have moved.
        records, _ = build(scan_files(), load_manifest())

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(dump(records), encoding="utf-8")
    print(f"Wrote {MANIFEST.relative_to(SITE_ROOT)} with {len(records)} document(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
